language: go
go:
  - 1.4.3
  - 1.5.3
  - tip
env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows
install:
  - go get golang.org/x/tools/cmd/vet
  - go get -v github.com/zquestz/s
script:
  - go build
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
