language: go
go:
  - 1.4.3
  - 1.5.3
  - tip
env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows
install:
  - go get golang.org/x/tools/cmd/vet
  - go get -v github.com/zquestz/s
script:
  - go build
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
after_script:
  - if [ "$TRAVIS_GO_VERSION" = "1.5.3" ] && [ "$BUILD_GOOS" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/inconshreveable/mousetrap; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.5.3" ] && [ "$BUILD_GOOS" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/mitchellh/gox; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.5.3" ] && [ "$BUILD_GOOS" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/tcnksm/ghr; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.5.3" ] && [ "$BUILD_GOOS" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then make compile; ghr --username samurai20000 --token $GITHUB_TOKEN --replace $TRAVIS_TAG pkg/; fi
